/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AINode: typeof import('./src/components/AINode.vue')['default']
    AIPlanNode: typeof import('./src/components/AIPlanNode.vue')['default']
    AudioNode: typeof import('./src/components/AudioNode.vue')['default']
    ChangePwd: typeof import('./src/components/ChangePwd.vue')['default']
    CommandsList: typeof import('./src/components/CommandsList.vue')['default']
    Draw: typeof import('./src/components/Draw.vue')['default']
    EchartsBar: typeof import('./src/components/EchartsBar.vue')['default']
    EchartsLine: typeof import('./src/components/EchartsLine.vue')['default']
    EchartsPie: typeof import('./src/components/EchartsPie.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTour: typeof import('element-plus/es')['ElTour']
    ElTourStep: typeof import('element-plus/es')['ElTourStep']
    ImgPlaceholder: typeof import('./src/components/uploadImage/imgPlaceholder.vue')['default']
    InputPlus: typeof import('./src/components/InputPlus.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MermaidNode: typeof import('./src/components/MermaidNode.vue')['default']
    OCRResult: typeof import('./src/components/OCRResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineNode: typeof import('./src/components/TimelineNode.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
